const items = [
  {
    id: 1,
    tam: "அரிசி",
    sin: "සහල්",
    eng: "Rice",
    max: 10,
    unit: "KG",
    quantity: 1,
    price: 188,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/rice_rjUkfspMqs.png?updatedAt=1696814724545",
  },
  {
    id: 2,
    tam: "கோ. மாவு",
    sin: "තිරිඟු පිටි",
    eng: "Wheat Flour",
    max: 8,
    unit: "KG",
    quantity: 8,
    price: 200,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/flour_SfJ49Wp91.png?updatedAt=1696814718461",
  },
  {
    id: 3,
    tam: "அ. மாவு",
    sin: "හාල් පිටි",
    eng: "Rice Flour",
    max: 5,
    unit: "KG",
    quantity: 1,
    price: 218,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/rice-flour_JtPGjqtId.png?updatedAt=1696814724190",
  },
  {
    id: 4,
    tam: "தேயிலை",
    sin: "තේ කොළ",
    eng: "Tea",
    max: 1,
    unit: "G",
    quantity: 500,
    price: 750,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/tea_1ETJXJwoE.png?updatedAt=1696814730270",
  },
  {
    id: 5,
    tam: "சீனி",
    sin: "සීනි",
    eng: "Sugar",
    max: 3,
    unit: "KG",
    quantity: 1,
    price: 268,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/sugar_-r91qvSpYJ.png?updatedAt=1696814731959",
  },
  {
    id: 6,
    tam: "பெ. வெங்காயம்",
    sin: "ලොකු ලූනු",
    eng: "Big onion",
    max: 2,
    unit: "KG",
    quantity: 2,
    price: 220,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/onion_Ldogt0yQy.png?updatedAt=1696814719091",
  },
  {
    id: 7,
    tam: "பா.பயறு",
    sin: "මුං ඇට",
    eng: "Green Gramme",
    max: 1,
    unit: "KG",
    quantity: 1,
    price: 1000,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/green_pS-BTt8Pl.png?updatedAt=1696814718843",
  },
  {
    id: 8,
    tam: "பருப்பு",
    sin: "මයිසූර් පරිප්පු",
    eng: "Red Dhal",
    max: 7,
    unit: "G",
    quantity: 500,
    price: 110,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/dhal_09vNGBln0.png?updatedAt=1696814718977",
  },
  {
    id: 9,
    tam: "கடலை",
    sin: "කඩල",
    eng: "Chick Pease",
    max: 1,
    unit: "KG",
    quantity: 1,
    price: 650,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/chick_7bH_EKoXr.png?updatedAt=1696814710252",
  },
  {
    id: 10,
    tam: "உ.கிழங்கு",
    sin: "අල",
    eng: "Potatoes",
    max: 2,
    unit: "KG",
    quantity: 1,
    price: 190,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/potatoe_UGnpym2U45.png?updatedAt=1696814719989",
  },
  {
    id: 11,
    tam: "ரின் மீன்",
    sin: "ටින් මාළු",
    eng: "Dry fish",
    max: 2,
    unit: "TIN",
    quantity: "1",
    price: 650,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/dryFish_NCR6dFnxx.png?updatedAt=1696814715906",
  },
  {
    id: 12,
    tam: "முட்டை",
    sin: "බිත්තර",
    eng: "Eggs",
    max: 20,
    unit: "Egg",
    quantity: 1,
    price: 20,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/egg_EdDy8rxjJ.png?updatedAt=1696814715933",
  },
  {
    id: 13,
    tam: "உப்பு",
    sin: "ලුණු",
    eng: "Salt",
    max: 1,
    unit: "PKT",
    quantity: 1,
    price: 110,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/salt_7Vw2qtSclb.png?updatedAt=1696814726865",
  },
  {
    id: 14,
    tam: "தே.எண்ணெய்",
    sin: "පොල් තෙල්",
    eng: "Coconut oil",
    max: 2,
    unit: "L",
    quantity: 1,
    price: 550,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/coconut-oil_lGfWPTilOV.png?updatedAt=1696814709381",
  },
  {
    id: 15,
    tam: "சோயா",
    sin: "සෝයා",
    eng: "Soya",
    max: 1,
    unit: "G",
    quantity: 1,
    price: 300,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/soya_TSnqdrqeY.jpg?updatedAt=1696814726868",
  },
  {
    id: 16,
    tam: "மிளகாய் தூள்",
    sin: "මිරිස් කුඩු",
    eng: "Chilly Powder",
    max: 1,
    unit: "G",
    quantity: 250,
    price: 375,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/red-chilly-powder_CJ_2f6-ftH.png?updatedAt=1696814721031",
  },
  {
    id: 17,
    tam: "மஞ்சள் தூள்",
    sin: "කහ",
    eng: "Turmeric",
    max: 1,
    unit: "G",
    quantity: 50,
    price: 125,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/turmeric_QERixc1AN.png?updatedAt=1696814731602",
  },
  {
    id: 18,
    tam: "கறி பவுடர்",
    sin: "තුනපහ කුඩු",
    eng: "Curry Powder",
    max: 1,
    unit: "G",
    quantity: 250,
    price: 500,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/curryPowder_ip6z1DtU_.png?updatedAt=1697607820750",
  },
  {
    id: 19,
    tam: "செத்தல்",
    sin: "මිරිස්",
    eng: "Dry Chilly",
    max: 1,
    unit: "G",
    quantity: 1,
    price: 275,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/dry-chilly_EVjPkcoHV.png?updatedAt=1696814711255",
  },
  {
    id: 20,
    tam: "மல்லி",
    sin: "කොත්තමල්ලි",
    eng: "Coriander",
    max: 1,
    unit: "G",
    quantity: 250,
    price: 100,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/coriander_DZT0HELjpg.png?updatedAt=1696814719179",
  },
  {
    id: 21,
    tam: "மிளகு",
    sin: "ගම්මිරිස්",
    eng: "Pepper",
    max: 1,
    unit: "G",
    quantity: 50,
    price: 120,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/pepper_ZloEcrt8W7.png?updatedAt=1696814719625",
  },
  {
    id: 22,
    tam: "பூண்டு",
    sin: "සුදුලූණු",
    eng: "Garlic",
    max: 1,
    unit: "G",
    quantity: 500,
    price: 210,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/garlic_f9116asNV.png?updatedAt=1696814711476",
  },
  {
    id: 23,
    tam: "லைப் போய்",
    sin: "ලයිෆ්බෝය්  සබන්",
    eng: "LifeBouy Soap",
    max: 2,
    unit: "PKT",
    quantity: 1,
    price: 160,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/soap_9IyRG-cUM.png?updatedAt=1696814731433",
  },
  {
    id: 23,
    tam: "Baby Soap",
    sin: "බේබි සබන්",
    eng: "Baby Soap",
    max: 2,
    unit: "PKT",
    quantity: 1,
    price: 160,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/soap_9IyRG-cUM.png?updatedAt=1696814731433",
  },
  {
    id: 24,
    tam: "ஈவா",
    sin: "ඊවා",
    eng: "Eva",
    max: 2,
    unit: "PKT",
    quantity: 1,
    price: 270,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/disposable-pads_bqTrvyLui.png?updatedAt=1696814706559",
  },
  {
    id: 25,
    tam: "பனதால்",
    sin: "පැනඩෝල්",
    eng: "Panadol",
    max: 2,
    unit: "CRD",
    quantity: 1,
    price: 50,
    image:
      "https://ik.imagekit.io/qsfifxkbx/Comodities/Panadol_F4TrGoXOZz.jpg?updatedAt=1696814716558",
  },
];
export default items;